name: 'Automerge Dependabot'

on:
  pull_request_target:
    types: [ opened, reopened ]
    branches:
    - dev
    - master

concurrency:
  group: "dependabot-automerge-${{ github.head_ref || github.run_id }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  automerge:
    name: Enable Automerge on Dependabot PRs
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.id == 49699333
    steps:
      - name: Tool Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd tools/Tgstation.Server.DeploymentsTool
          dotnet publish -c Release -o ${{ runner.temp }}/tool

      - name: Generate App Token
        run: |
          dotnet ${{ runner.temp }}/tool/Tgstation.Server.DeploymentsTool.dll ${{ secrets.TGS_CI_GITHUB_APP_TOKEN_SERIALIZED }} token ${{ runner.temp }}/installation_secret.txt
          echo "INSTALLATION_TOKEN=$(cat ${{ runner.temp }}/installation_secret.txt)" >> $GITHUB_ENV
          rm ${{ runner.temp }}/installation_secret.txt

      - name: Enable Automerge
        uses: daneden/enable-automerge-action@f8558b65c5b8d8bfb592c4e74e3d491624a38fbd #v1.0.2-ish
        with:
          github-token: ${{ env.INSTALLATION_TOKEN }}
