name: TGS Deployments Periodic Cleanup

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

concurrency:
  group: "periodic-cleanup"

jobs:
  report_version:
    name: Clean up Unresponsive Installations
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Tool Checkout
        uses: actions/checkout@v4
        with:
          path: temp_workspace

      - name: Build
        run: |
          cd temp_workspace/tools/Tgstation.Server.DeploymentsTool
          dotnet publish -c Release -o ${{ runner.temp }}/tool

      - name: Generate App Token
        id: app-token-generation
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Main Checkout
        uses: actions/checkout@v4
        with:
          ref: data
          token: ${{ steps.app-token-generation.outputs.token }}

      - name: Update Deployments
        run: dotnet ${{ runner.temp }}/tool/Tgstation.Server.DeploymentsTool.dll ${{ steps.app-token-generation.outputs.token }} cleanup

      - name: Git Config
        run: |
          git config user.name "tgstation-server-ci[bot]"
          git config user.email "161980869+tgstation-server-ci[bot]@users.noreply.github.com"

      - name: Git Stage
        run: git add .

      - name: Git Commit
        run: |
          git diff-index --quiet HEAD || git commit -m 'Cleanup Telemetry Entries' -m 'Job: ${{ github.run_id }}'

      - name: Git Push
        run: |
          git push -u origin data
