name: TGS Deployments Telemetry

on:
  workflow_dispatch:
    inputs:
      telemetry_id:
        description: 'Telemetry ID'
        required: true
        type: string
      tgs_semver:
        description: 'TGS Version'
        required: true
        type: string
      shutdown:
        description: 'Shutdown'
        required: true
        type: boolean
      server_friendly_name:
        description: 'Server Friendly Name'
        type: string

concurrency:
  group: "report-version"

jobs:
  report_version:
    name: Report TGS Version
    runs-on: ubuntu-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Tool Checkout
      uses: actions/checkout@v4
      with:
        path: temp_workspace

    - name: Restore
      run: |
        cd temp_workspace
        dotnet restore

    - name: Build
      run: |
        cd temp_workspace
        dotnet build -c Release

    - name: Generate App Token
      run: |
        cd temp_workspace
        dotnet run -c Release --no-build --project tools/Tgstation.Server.DeploymentsTool ${{ secrets.TGS_CI_GITHUB_APP_TOKEN_SERIALIZED }} token ${{ runner.temp }}/installation_secret.txt
        echo "INSTALLATION_TOKEN=$(cat ${{ runner.temp }}/installation_secret.txt)" >> $GITHUB_ENV
        rm ${{ runner.temp }}/installation_secret.txt

    - name: Main Checkout
      uses: actions/checkout@v4
      with:
        ref: data
        token: ${{ env.INSTALLATION_TOKEN }}

    - name: Update Deployments
      env:
        TELEMETRY_ID: ${{ github.event.inputs.telemetry_id }}
        TGS_SEMVER: ${{ github.event.inputs.tgs_semver }}
        SHUTDOWN: ${{ github.event.inputs.shutdown }}
        SERVER_FRIENDLY_NAME: ${{ github.event.inputs.server_friendly_name }}
      run: dotnet run -c Release --no-build --project temp_workspace/tools/Tgstation.Server.DeploymentsTool ${{ secrets.TGS_CI_GITHUB_APP_TOKEN_SERIALIZED }} telemetry

    - name: Git Config
      run: |
        git config user.name "tgstation-server-ci[bot]"
        git config user.email "161980869+tgstation-server-ci[bot]@users.noreply.github.com"

    - name: Git Commit
      run: |
        git add .
        git commit -m 'Update Telemetry Entry ${{ github.event.inputs.telemetry_id }}"

    - name: Git Push
      run: |
        git push -u origin data

