name: 'Tool Build'

on:
  push:
    branches:
    - main

jobs:
  tool-build:
    name: Build Deployments Tool
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [ 'Debug', 'Release' ]
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
